name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install frontend dependencies
      run: |
        cd client
        npm ci

    - name: Build frontend
      run: |
        cd client
        npm run build

    - name: Lint frontend
      run: |
        cd client
        npm run lint || true

    - name: Install backend dependencies
      run: |
        cd server
        npm ci

    - name: Run backend tests
      run: |
        cd server
        npm run test:coverage
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        NODE_ENV: test

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        directory: ./server/coverage
        fail_ci_if_error: true

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install backend dependencies
      run: |
        cd server
        npm ci

    - name: Build backend
      run: |
        cd server
        npm run build

    - name: Install frontend dependencies
      run: |
        cd client
        npm ci

    - name: Build frontend
      run: |
        cd client
        npm run build

    # Add your deployment steps here
    # For example, deploying to Heroku:
    # - name: Deploy to Heroku
    #   uses: akhileshns/heroku-deploy@v3.12.12
    #   with:
    #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
    #     heroku_app_name: "your-app-name"
    #     heroku_email: "your-email@example.com" 