version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@db:5432/minhon
      - REDIS_URL=redis://redis:6379
      - PORT=10000
      - JWT_SECRET=your_jwt_secret
      - SENTRY_DSN=your_sentry_dsn
    ports:
      - "10000:10000"
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: minhon
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  db_backup:
    image: postgres:14
    depends_on:
      - db
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data:ro
      - db_backup:/backup
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "while true; do pg_dump -h db -U postgres minhon > /backup/backup_$(date +%Y%m%d_%H%M%S).sql; sleep 86400; done"
    restart: unless-stopped

volumes:
  db_data:
  redis_data:
  db_backup:
